source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

inhibit_all_warnings!

pod 'GoogleAnalytics'
pod 'AFNetworking'
pod 'YKImageCropper'
pod 'ACEDrawingView'
pod 'CWStatusBarNotification'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'PonyDebugger'
pod 'googleplus-ios-sdk'
pod 'Masonry'
pod 'RSKImageCropper'
pod 'SVProgressHUD'
pod 'SSKeychain'
pod 'pop'
pod 'IQKeyboardManager'
pod 'SZTextView'
pod 'SDWebImage'
pod 'SDiPhoneVersion'
pod 'AutoScrollLabel'
pod 'Analytics/Segmentio'
pod 'TOWebViewController'
pod 'Crashlytics'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'Fabric'
pod 'Onboard'