/* Generated document. DO NOT CHANGE */

NSString * const CAMERA_CONTAINER_SEGUE = @"CAMERA_CONTAINER_SEGUE";

NSString * const CAMERA_NAV_VC = @"CAMERA_NAV_VC";
NSString * const CAMERA_VC = @"CAMERA_VC";
NSString * const PHOTO_CONTAINER_VC = @"PHOTO_CONTAINER_VC";
NSString * const VIDEO_CONTAINER_VC = @"VIDEO_CONTAINER_VC";
