# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.0.2"

default_platform :ios 


platform :ios do

  before_all do
    # Set Slack URL
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"

    # Must setup this first: https://developer.apple.com/library/ios/qa/qa1827/_index.html
    if ENV["BUILD_NUMBER"]
      increment_build_number(
      build_number: ENV["BUILD_NUMBER"].to_i
      )
    else
      increment_build_number
    end

    #Pod install
    cocoapods

    #Install Rollout
    #sh "../Pods/Rollout.io/install/configure_pod.sh -k 5435744b2f554a1076b7bbfe"

  end

  desc "Runs all the tests"
  lane :test do
    xctest
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # snapshot
    cert
    sigh(
      force: true
    )
    # Build
    ipa(
      workspace: "uSnap.xcworkspace",
      configuration: "Release",
      scheme: "uSnap",
      clean: false,
    )
    resign(
      signing_identity: "iPhone Distribution: uSnap Media Inc. (6WH26365Q4)",
    )
    deliver(
       skip_deploy: true,
       beta: true
   )
  end

desc "Submit a new Beta Build to Apple TestFlight"
desc "This will also make sure the profile is up to date"
lane :'beta neomedia' do
# snapshot
cert
sigh(
force: true
)
# Build
ipa(
workspace: "uSnap.xcworkspace",
configuration: "Release",
scheme: "Neomedia",
clean: false,
)
resign(
signing_identity: "iPhone Distribution: uSnap Media Inc. (6WH26365Q4)",
)
deliver(
skip_deploy: true,
beta: true
)
end

  desc "Deploy a new version to the App Store"
  desc "** Full Markdown** Support: `code`"
  lane :deploy do
    # snapshot
    sigh
    # deliver :skip_deploy, :force
    # frameit
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    slack({
      message: "Build successful.",
      success: true,
      channel: 'snapzi-ios'
    })
  end


  error do |lane, exception|
  slack({
     message: "Build error: #{exception.message}",
     success: false,
     channel: 'snapzi-ios'
   })
  end  
end

# More information about multiple platforms in fastlane: 
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
